name: Core
main: net.sacredlabyrinth.Phaed.Core.Core
version: 1.3
commands:
  time:
    description: 
    usage:
  i:
    description: 
    usage:
  item:
    description: 
    usage:
  ims:
    description: 
    usage:
  items:
    description: 
    usage:
  give:
    description: 
    usage:
  who:
    description: 
    usage:
  list:
    description: 
    usage:
  clear:
    description: 
    usage:
  msg:
    description: 
    usage:
  m:
    description: 
    usage:
  plugin:
    description: 
    usage:    