name: Core
main: net.sacredlabyrinth.Phaed.Core.Core
version: 1.5.3
softdepend: [PermissionsBukkit, VanishNoPacket, mChat, mChatSuite]
commands:
  setrank:
    description: command
  setvip:
    description: command
  lockdown:
    description: command
  data:
    description: command
  sun:
    description: command
  storm:
    description: command
  day:
    description: command
  night:
    description: command
  i:
    description: command
  item:
    description: command
  ims:
    description: command
  items:
    description: command
  give:
    description: command
  who:
    description: command
  maxxp:
    description: command
  list:
    description: command
  clear:
    description: command
  msg:
    description: command
  m:
    description: command
  plugin:
    description: command
  coords:
    description: command
permissions:
  core.lockdown:
    description: description
  core.lockup:
    description: description
  core.data:
    description: description
  core.day:
    description: description
  core.night:
    description: description
  core.item:
    description: description
  core.items:
    description: description
  core.give:
    description: description
  core.who:
    description: description
  core.msg:
    description: description
  core.clear:
    description: description
  core.plugin:
    description: description
  core.setrank:
    description: description
  core.setvip:
    description: description
  core.*:
    default: false
    description: description
    children:
      core.lockdown: true
      core.lockup: true
      core.data: true
      core.day: true
      core.night: true
      core.item: true
      core.items: true
      core.give: true
      core.who: true
      core.msg: true
      core.clear: true
      core.plugin: true
      core.setrank: true
      core.setvip: true