name: Core
main: net.sacredlabyrinth.Phaed.Core.Core
version: 1.4.5
softdepend: [PermissionsBukkit, VanishNoPacket, mChat]
commands:
  lockdown:
    description:
  data:
    description:
  day:
    description:
  night:
    description:
  i:
    description:
  item:
    description:
  ims:
    description:
  items:
    description:
  give:
    description:
  who:
    description:
  maxxp:
    description:      
  list:
    description:
  clear:
    description:
  msg:
    description:
  m:
    description:
  plugin:
    description:
  coords:
    description:
permissions:
  core.lockdown:
    description:
  core.lockup:
    description:
  core.data:
    description:
  core.day:
    description:
  core.night:
    description:
  core.item:
    description:
  core.items:
    description:
  core.give:
    description:
  core.who:
    description:
  core.msg:
    description:
  core.clear:
    description:
  core.plugin:
    description:
