name: Core
main: net.sacredlabyrinth.Phaed.Core.Core
version: 1.5.7
softdepend: [PermissionsBukkit, VanishNoPacket, mChat, mChatSuite]
commands:
  setrank:
    description: setrank
  setvip:
    description: setVIP
  lockdown:
    description: lockdown server
  data:
    description: get data
  sun:
    description: set sun
  storm:
    description: set storm
  day:
    description: set day
  night:
    description: set night
  i:
    description: give item
  item:
    description: give item
  ims:
    description: give items
  items:
    description: give items
  give:
    description: give items
  who:
    description: use /who
  maxxp:
    description: give XP
  list:
    description: use /who
  clear:
    description: clear inventory
  msg:
    description: use /msg
  m:
    description: use /m
  plugin:
    description: show plugin commands
  coords:
    description: give user coords
permissions:
  core.lockdown:
    description: lockdown server
  core.lockup:
    description: lockup server
  core.data:
    description: show data
  core.day:
    description: set day
  core.night:
    description: set night
  core.item:
    description: give item
  core.items:
    description: give items
  core.give:
    description: give items
  core.who:
    description: use /who
  core.msg:
    description: send a /msg
  core.clear:
    description: clear inventory
  core.plugin:
    description: use plugin commands
  core.setrank:
    description: setrank!
  core.setvip:
    description: setvip
  core.*:
    default: false
    description: description
    children:
      core.lockdown: true
      core.lockup: true
      core.data: true
      core.day: true
      core.night: true
      core.item: true
      core.items: true
      core.give: true
      core.who: true
      core.msg: true
      core.clear: true
      core.plugin: true
      core.setrank: true
      core.setvip: true