name: Core
main: net.sacredlabyrinth.Phaed.Core.Core
version: 1.5.3
softdepend: [PermissionsBukkit, VanishNoPacket, mChat, mChatSuite]
commands:
  setrank:
    description:
  setvip:
    description:
  lockdown:
    description:
  data:
    description:
  sun:
    description:
  storm:
    description:
  day:
    description:
  night:
    description:
  i:
    description:
  item:
    description:
  ims:
    description:
  items:
    description:
  give:
    description:
  who:
    description:
  maxxp:
    description:
  list:
    description:
  clear:
    description:
  msg:
    description:
  m:
    description:
  plugin:
    description:
  coords:
    description:
permissions:
  core.lockdown:
    description:
  core.lockup:
    description:
  core.data:
    description:
  core.day:
    description:
  core.night:
    description:
  core.item:
    description:
  core.items:
    description:
  core.give:
    description:
  core.who:
    description:
  core.msg:
    description:
  core.clear:
    description:
  core.plugin:
    description:
  core.setrank:
    description:
  core.setvip:
    description:
  core.*:
    default: false
    description:
    children:
      core.lockdown: true
      core.lockup: true
      core.data: true
      core.day: true
      core.night: true
      core.item: true
      core.items: true
      core.give: true
      core.who: true
      core.msg: true
      core.clear: true
      core.plugin: true
      core.setrank: true
      core.setvip: true